version: '3.1'
services:
  rabbitmq:
    image: rabbitmq:3.13.7-management
    container_name: rabbitmq_3_12
    restart: always
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data:/var/lib/rabbitmq
      - ./myplugins:/etc/rabbitmq/myplugins
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
